# Generated by Django 6.0.5 on 2026-06-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_translator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('title', 'Title'), ('table', 'Table'), ('list', 'List'), ('footer', 'Footer'), ('header', 'Header'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('ocr', 'OCR')], default='manual', max_length=20)),
                ('source_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('bbox_x', models.PositiveIntegerField()),
                ('bbox_y', models.PositiveIntegerField()),
                ('bbox_width', models.PositiveIntegerField()),
                ('bbox_height', models.PositiveIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_blocks', to='document_translator.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_blocks', to='document_translator.documentpage')),
            ],
            options={
                'ordering': ['page__page_number', 'bbox_y', 'bbox_x'],
            },
        ),
    ]
