# Generated by Django 6.0.5 on 2026-06-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_translator', '0002_translationblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('title', 'Title'), ('paragraph', 'Paragraph'), ('list', 'List'), ('table', 'Table'), ('header', 'Header'), ('footer', 'Footer'), ('signature', 'Signature'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual'), ('ocr', 'OCR')], default='ai', max_length=20)),
                ('source_text', models.TextField(blank=True)),
                ('bbox_x', models.PositiveIntegerField()),
                ('bbox_y', models.PositiveIntegerField()),
                ('bbox_width', models.PositiveIntegerField()),
                ('bbox_height', models.PositiveIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='document_translator.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='document_translator.documentpage')),
            ],
            options={
                'ordering': ['page__page_number', 'bbox_y', 'bbox_x'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField(blank=True)),
                ('target_x', models.PositiveIntegerField(default=0)),
                ('target_y', models.PositiveIntegerField(default=0)),
                ('target_width', models.PositiveIntegerField(default=0)),
                ('target_height', models.PositiveIntegerField(default=0)),
                ('html', models.TextField(blank=True)),
                ('css', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='document_translator.documentblock')),
            ],
            options={
                'ordering': ['block__page__page_number', 'target_y', 'target_x'],
            },
        ),
        migrations.DeleteModel(
            name='TranslationBlock',
        ),
    ]
