# Generated by Django 6.0.5 on 2026-06-05 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_translator', '0003_documentblock_documentblocktranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual'), ('initial', 'Initial')], default='ai', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('archived', 'Archived'), ('discarded', 'Discarded')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_analyses', to='document_translator.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='document_translator.documentpage')),
            ],
            options={
                'ordering': ['page__page_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentblock',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='document_translator.documentpageanalysis'),
        ),
    ]
