# Generated by Django 6.0.5 on 2026-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_translator', '0004_documentpageanalysis_documentblock_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpageanalysis',
            options={'ordering': ['page__page_number', 'created_at']},
        ),
        migrations.AlterField(
            model_name='documentpageanalysis',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('archived', 'Archived'), ('discarded', 'Discarded'), ('accepted', 'Accepted legacy')], default='draft', max_length=20),
        ),
    ]
